codecov:
  # Enable the Codecov bot comment on pull requests
  notify:
    require_ci_to_pass: yes

coverage:
  # Exclude files or directories from coverage calculation
  ignore:
    - "test/*"  # Exclude test files
    - "*.md"    # Exclude markdown files like README.md

  status:
    project:
      default:   # default is the status check's name, not default settings
        target: auto 
        threshold: 5
        base: auto 
        flags: 
          - unit
        paths: 
          - "src"
        # advanced settings
        branches: 
          - main
        if_ci_failed: error #success, failure, error, ignore
        informational: false
        only_pulls: false