name = "SpectralDeferredCorrections"
uuid = "18b2da82-ce85-419b-a263-4a22af66788b"
authors = ["Lisa Wimmer"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Coverage = "aa819f9c-3301-55e2-850d-134aab1a5b97"

[targets]
test = ["Test"]
