name: CI pipeline - SpectralDeferredCorrections.jl

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    name: Test Julia
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Julia
      uses: julia-actions/setup-julia@v2
      with:
        version: '1.11.2'

    - name: Install dependencies
      run: julia --project=@. -e 'using Pkg; Pkg.instantiate(); Pkg.precompile()'

    - name: Run tests with coverage
      run: julia --project=@. --code-coverage test/runtests.jl

    - name: Process coverage
      uses: julia-actions/julia-processcoverage@v1
      with:
        input: src  # Directory to process raw coverage data from
        output: lcov.info  # Output file name

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./lcov.info
        fail_ci_if_error: true
