name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Julia
      uses: julia-actions/setup-julia@v1
      with:
        version: '1.9'

    - name: Install dependencies
      run: julia --project=@. -e 'using Pkg; Pkg.instantiate()'

    - name: Install Coverage dependency
      run: julia --project=@. -e 'using Pkg; Pkg.add("Coverage")'

    - name: Run tests with coverage
      run: julia --project=@. --code-coverage test/runtests.jl

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: lcov.info
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: lcov.info

