name: CI pipeline - SpectralDeferredCorrections.jl

on: [push, pull_request]

jobs:
  test:
    name: Julia 11.1.2 with Python ${{matrix.python}} on ${{ matrix.os }}  - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        julia-version:
          - 1.11.2
        python: [3.11]
        os:
          - macOS-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Set ENV Variables for Python
        run: echo ENV["PYTHON"] = `which python` >> $GITHUB_ENV

      - name: Install pip and qmat
        run: |
          python -m pip install --upgrade pip
          pip install qmat

      - name: Set up Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.julia-version }}

      - uses: julia-actions/julia-buildpkg@v1
        env:
          PYTHON : "${{ env.pythonLocation }}/bin/python"

      - name: Run tests with coverage
        run: julia --project=@. --code-coverage test/runtests.jl
    
      - name: Process coverage
        uses: julia-actions/julia-processcoverage@v1
        with:
          input: src
          output: lcov.info
    
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./lcov.info
          fail_ci_if_error: true
