name: CI pipeline - SpectralDeferredCorrections.jl

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    name: Julia 1.11.2 on macOS
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Julia
      uses: julia-actions/setup-julia@v2
      with:
        version: '1.11.2'

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniforge-version: "latest"
        environment-file: environment.yml
        activate-environment: qmat_dependency
        use-mamba: false

    - name: Debug Python Environment
      run: |
        source "$(conda info --base)/etc/profile.d/conda.sh"
        conda activate qmat_dependency
        python --version
        python -c "import encodings; print('Encodings module found')"

    - name: Configure PyCall
      run: |
        source "$(conda info --base)/etc/profile.d/conda.sh"
        conda activate qmat_dependency
        julia --project=@. -e 'ENV["PYTHON"] = joinpath(read(`conda info --base`, String) |> chomp, "envs", "qmat_dependency", "bin", "python"); using Pkg; Pkg.build("PyCall")'

    - name: Debug Python Path
      run: |
        source "$(conda info --base)/etc/profile.d/conda.sh"
        conda activate qmat_dependency
        echo $PATH
        python -c "import encodings; print('Encodings module works!')"      

    - name: Install Julia dependencies
      run: julia --project=@. -e 'using Pkg; Pkg.instantiate(); Pkg.precompile()'

    - name: Run tests with coverage
      run: julia --project=@. --code-coverage test/runtests.jl

    - name: Process coverage
      uses: julia-actions/julia-processcoverage@v1
      with:
        input: src
        output: lcov.info

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./lcov.info
        fail_ci_if_error: true
