name: CI pipeline - SpectralDeferredCorrections.jl

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    name: Julia 1.11.2 on macOS
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Julia
      uses: julia-actions/setup-julia@v2
      with:
        version: '1.11.2'

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.11
        environment-file: environment.yml
        activate-environment: qmat_dependency

    - name: Configure PyCall to use Conda Python
      run: |
        julia --project=@. -e 'ENV["PYTHON"] = "$(conda info --base)/envs/qmat_dependency/bin/python"; using Pkg; Pkg.build("PyCall")'

    - name: Debug Python environment
      run: |
        conda activate qmat_dependency
        which python
        python --version
        python -c "import qmat; print('qmat module imported successfully')"

    - name: Install dependencies
      run: julia --project=@. -e 'using Pkg; Pkg.instantiate(); Pkg.precompile()'

    - name: Run tests with coverage
      run: julia --project=@. --code-coverage test/runtests.jl

    - name: Process coverage
      uses: julia-actions/julia-processcoverage@v1
      with:
        input: src  # Directory to process raw coverage data from
        output: lcov.info  # Output file name

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./lcov.info
        fail_ci_if_error: true
